formatter: "md table"

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # Coolify worker module

  This is a module for deploying a coolify worker (VM) including a network security group, public ip address etc.

  {{ .Header }}

  {{ .Inputs }}

  {{ .Outputs }}

  # Examples

  ## Default
  ```hcl
  {{ include "examples/default/main.tf" }}
  ```

output:
  file: "README.md"
  path: "."

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: false
  read-comments: true
  required: true
  sensitive: true
  type: true
